(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.TechnologyViewport=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const finite=value=>Number.isFinite(Number(value))?Number(value):null;
  function graphBounds(nodes=[],edges=[],nodeWidth=184,nodeHeight=86){const boxes=[];for(const node of nodes){const x=finite(node?.x),y=finite(node?.y),w=Math.max(1,finite(node?.width)??nodeWidth),h=Math.max(1,finite(node?.height)??nodeHeight);if(x===null||y===null)continue;boxes.push({minX:x-w/2,maxX:x+w/2,minY:y-h/2,maxY:y+h/2})}for(const edge of edges){for(const point of[edge?.source,edge?.target,...(Array.isArray(edge?.points)?edge.points:[])]){const x=finite(point?.x),y=finite(point?.y);if(x!==null&&y!==null)boxes.push({minX:x,maxX:x,minY:y,maxY:y})}}if(!boxes.length)return{minX:0,maxX:0,minY:0,maxY:0,width:0,height:0,empty:true};const minX=Math.min(...boxes.map(x=>x.minX)),maxX=Math.max(...boxes.map(x=>x.maxX)),minY=Math.min(...boxes.map(x=>x.minY)),maxY=Math.max(...boxes.map(x=>x.maxY));return{minX,maxX,minY,maxY,width:maxX-minX,height:maxY-minY,empty:false}}
  function workspace(bounds,padding=120){const pad=Math.max(0,finite(padding)??120);return{offsetX:pad-bounds.minX,offsetY:pad-bounds.minY,width:Math.max(1,bounds.width+pad*2),height:Math.max(1,bounds.height+pad*2),padding:pad}}
  function fitScale(bounds,viewportWidth,viewportHeight,{padding=48,min=.4,max=1.5}={}){const width=Math.max(1,bounds.width+padding*2),height=Math.max(1,bounds.height+padding*2),vw=Math.max(1,finite(viewportWidth)??1),vh=Math.max(1,finite(viewportHeight)??1);return Math.max(min,Math.min(max,vw/width,vh/height))}
  function zoomAround(scrollLeft,scrollTop,cursorX,cursorY,oldScale,newScale){const old=Math.max(.01,finite(oldScale)??1),next=Math.max(.01,finite(newScale)??1),x=Math.max(0,finite(cursorX)??0),y=Math.max(0,finite(cursorY)??0);return{left:(scrollLeft+x)*next/old-x,top:(scrollTop+y)*next/old-y}}
  function outsideCount(nodes,bounds){return nodes.filter(node=>{const x=finite(node?.x),y=finite(node?.y),w=Math.max(1,finite(node?.width)??184),h=Math.max(1,finite(node?.height)??86);return x===null||y===null||x-w/2<bounds.minX||x+w/2>bounds.maxX||y-h/2<bounds.minY||y+h/2>bounds.maxY}).length}
  return{finite,graphBounds,workspace,fitScale,zoomAround,outsideCount};
});
